name: Update stars
on:
  schedule:
    - cron: "8 */5 1-25 12 *"  # At minute 8 every 5th hour in December.
  workflow_dispatch:
jobs:
  update-stars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 1506714
          sessionCookie: ${{ secrets.AOC_SESSION }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update readme
